### PR TITLE
WIP: Test create

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Based on https://github.com/zchee/docker-machine-driver-xhyve/pull/28

### CODE REVIEW

**Comment by zchee** [comment]
@johanneswuerbach Thakns some PR.

Is this PR a mergeable state?

**Comment by johanneswuerbach** [comment]
Not yet,, sorry.

**Comment by zchee** [comment]
@johanneswuerbach Ok.
I will wait :)

**Comment by zchee** [comment]
@johanneswuerbach Off topic, I was surprised that Travis is using VMware :hushed:
Possibly, travis you might have a `vmrun` and `vmware-vdiskmanager`...?

**Comment by johanneswuerbach** [comment]
Looks like travis is still not able to run it: `vmx_init: processor not supported by Hypervisor.framework` Would you be interested in the non-travis changes, like the improved B2D version parsing?

**Comment by zchee** [comment]
@johanneswuerbach Oh...
If the travis is really using the vmware, This is the same case as this result.
https://github.com/zchee/docker-machine-driver-xhyve/blob/master/README.md#would-you-do-me-a-favor on `In the case of VMWare`

**Comment by johanneswuerbach** [comment]
Extracted my two enhancements: https://github.com/zchee/docker-machine-driver-xhyve/pull/31 https://github.com/zchee/docker-machine-driver-xhyve/pull/32

**Pull request closed without merging**
