### PR TITLE
Move the NFS and 9p mounting code from Create to Start.

### PR DESCRIPTION
**Pull request by dlorenc**
This will re-mount on a re-start.

This should fix https://github.com/kubernetes/minikube/issues/1133

### CODE REVIEW

**Comment by zchee** [comment]
@dlorenc SGTM, also maybe I understand why it happened. Sorry, it's my mistake.
I'll check it. Thanks.

**Comment by dlorenc** [comment]
Hmm, we might need to keep this in both places actually. Trying to figure out the way the API works...

**Comment by zchee** [comment]
Hm, I have not seen the whole code yet, but that is possibility.
libmachine sometimes require redundant, such as implemented root binary check etc.

**Comment by dlorenc** [comment]
Yeah it looks like we do need this in both places. Refactored a bit. Sorry for the confusion.

**Comment by zchee** [comment]
@dlorenc np! I'll try to check and test it.

**Comment by zchee** [comment]
@dlorenc BTW, There are pull requests that support multiple NFS shares.
WDTY?

**Comment by dlorenc** [comment]
Seems reasonable, I'm not sure of the use-case though. Maybe some of that could be better handled with modifications of bootlocal.sh inside the iso? https://github.com/boot2docker/boot2docker/blob/master/doc/FAQ.md#local-customisation-with-persistent-partition

**Comment by zchee** [comment]
@dlorenc Yeah maybe needs to fix this line,
https://github.com/zchee/docker-machine-driver-xhyve/blob/46a94c2450c532fa766698ae8906cdc69933134a/xhyve/xhyve.go#L933-L937
but that pull request seems to already fix it.
OK, I'll also check that pull request together.

**Comment by zchee** [comment]
@dlorenc Ah, sorry, Are you said means had been changed boot2docker bootlocal.sh specification?

**Comment by zchee** [comment]
@dlorenc Anyway, this pull request is LGTM. The failed CI will fix.
Merged.

**Comment by zchee** [comment]
@dlorenc Thanks!!

**Comment by justechn** [comment]
Thanks for getting this fixed so quickly. Can we get a new build so I can use this?

**Comment by justechn** [comment]
@zchee @dlorenc Thanks for getting this fixed so quickly. Can we get a new release so I can use this?

**Comment by huguesalary** [comment]
I just created a [pull request](https://github.com/zchee/docker-machine-driver-xhyve/pull/194) that undoes all this work. Then I saw this issue.

Specifically [this commit](https://github.com/zchee/docker-machine-driver-xhyve/pull/194/commits/a1a2598507015364f3aa07f053d56e914ea3e944) in the PR reverts part of the work that was done in this thread.

Here's the commit message:

> Make sure both Virtio9p shared folders and NFS shared folders can be used at the same time.
> 
> In this commit I removed the `d.setupMount()` from the `Start()` function: `Start()` simply starts the docker-machine and isn't supposed to do any other work. For example, you can not add more CPUs, more RAM, or more Disks with the `docker-machine start` command. Just like CPU, RAM, etc, Shared Folders can not be added after the fact with `docker-machine start` and as such, the `d.setupMounts()` shouldn't run.
> 
> I, however, changed the `Create()` function so that it returns an error, and thus prevents the docker-machine from being created, when the `d.setupMounts()` fails.
> 
> The other changes address the bug where you couldn't have both Virtio9p *and* NFS shared folders. The bug was that both the code setting up Virtio9p shares and the NFS shares would overwrite the `bootlocal.sh` script.

As I explain in the commit message, it seems to me that `Start()` shouldn't call `setupMounts()`. Specifically, all `setupMounts()` does is fill the `bootlocal.sh` script with `mount` commands.

Once `bootlocal.sh` has been created (at the `docker-machine create` time), there's no need to ever re-create it (at `docker-machine start` time).

**Pull request merged**
