### PR TITLE
Defer the unmount.

### PR DESCRIPTION
**Pull request by dlorenc**
I had a couple cases where an error happened on line 608, then the iso never got unmounted so I couldn't properly delete the .minikube directory.

### CODE REVIEW

**Comment by zchee** [comment]
@dlorenc LGTM. I also have the same problem.

**Comment by zchee** [comment]
@dlorenc Just in case, it's ready to merge?
The merge process are
#143 -> #144 
OK?

**Comment by dlorenc** [comment]
Yup, I can rebase 144 after this goes in. I made them as separate branches that are derived from each other, not sure how github will handle this.

**Comment by zchee** [comment]
@dlorenc Okay, I'll merge it. please rebase if necessary.

**Comment by zchee** [comment]
@dlorenc Ah, this is PR for `zchee:minikube-iso_kexec`? I'm misunderstood.
ok, got it.

**Pull request merged**
