### PR TITLE
Support using the configured UUID instead of always generating a UUID…

### PR DESCRIPTION
**Pull request by chirino**
… so that you can reuse IP addresses for hosts.

### CODE REVIEW

**Comment by zchee** [comment]
@chirino Thanks for the pull request!

It seems LGTM, but now xhyve driver has not configure `UUID` flag.
Maybe this pull request for minikube or minishift?
I think better is also add `uuid` variable flag.

Thanks.

**Comment by chirino** [comment]
Yep it's related to minikube/shift see: https://github.com/jimmidyson/minishift/pull/53

**Comment by zchee** [comment]
@chirino Thanks :)
LGTM.

**Comment by zchee** [comment]
@chirino I'm wait for ci result...

**Comment by zchee** [comment]
@chirino @jimmidyson merged. Thanks :)

**Comment by zchee** [comment]
@jimmidyson yey \o/

**Comment by zchee** [comment]
@jimmidyson @dlorenc I think maybe kubenetes team and minikube/minishift like to use release version.
I will release the next version after some private works.

**Comment by jimmidyson** [comment]
We certainly do want to use it! Whenever you get a chance to release that would be great. Thanks!

**Pull request merged**
