### PR TITLE
Add glide tool as go dependency management

### PR DESCRIPTION
**Pull request by praveenkumar**
This will add glide as dependency management tool which will make easy to have 3rd party modules part of this repo. I also added step in README file. Give it a try.

### CODE REVIEW

**Comment by praveenkumar** [comment]
cc @zchee @dlorenc @r2d4

**Comment by zchee** [comment]
@praveenkumar I have short tested this pull request. LGTM.
In particular, included `jceel/lib9p` is great :)
I'll more testing.

**Comment by zchee** [comment]
@praveenkumar Ah, `vendor/lib9p` submodule is duplicate.
Could you try below? (But sorry, I do not know this is the correct way to delete git submodule)

```sh
git submodule deinit vendor/lib9p
git rm --cached vendor/lib9p
git rm .gitmodule
git add .gitmodule vendor/lib9p
.
.
```

**Comment by praveenkumar** [comment]
@zchee will check and let you know.

**Comment by praveenkumar** [comment]
@zchee removed lib9p submodule now.

**Comment by zchee** [comment]
@praveenkumar I'll check it. Thanks.

**Comment by zchee** [comment]
@praveenkumar LGTM. Thanks :D

**Pull request merged**
