### PR TITLE
Add check binary owner on PreCreateCheck()

### PR DESCRIPTION
**Pull request by zchee**
See also https://github.com/zchee/docker-machine-driver-xhyve/pull/75

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
This won't support `sudo docker-machine create -d xhyve` right? I would like if both cases are handled and the driver checks before every command `stop`, `restart` touching xhyve whether the permissions are correct. WDYT?

**Comment by zchee** [comment]
@johanneswuerbach That's correct.
`PreCreateCheck()` is only called when creating command.
I think need check owner before all commands such as `PreCommandCheck()`(or `PreOwnerCheck`?).
I will more fix when merged this PR.

but, Do we require corrective action of `sudo`?
Currently, there are users who would put the `sudo` before `docker-machine` command, but `docker-machine` other drivers are not instructed and put the `sudo`.
So, I think solve if I write a more detail usage.
When install by Homebrew, users do not know how to use and flags, they will see this repository.

Check of the owner is required.
and, If does not exists `$HOME/.docker` directory, `boot2docker.iso` file and `$HOME/.docker/machine/cache` directory will be create by `root` owner.
This problem is also required improve.

WDTY?

===

Sorry, I am sleepy, English is rough... :scream_cat:

**Comment by zchee** [comment]
@johanneswuerbach But put as insurance might be good!

**Comment by zchee** [comment]
@johanneswuerbach I created other issue.
It will tentatively merge this PR.

**Comment by johanneswuerbach** [comment]
Thanks, :bow:

**Comment by zchee** [comment]
@johanneswuerbach Create pull-request!
https://github.com/zchee/docker-machine-driver-xhyve/pull/78

Handling own binary owner, and `sudo` before `docker-machine` command.
It's probably working.

**Pull request merged**
