### PR TITLE
xhyve/qcow2: support qcow2 disk image format

### PR DESCRIPTION
**Pull request by zchee**
Support QEMU qcow2 disk image format use [zchee/go-qcow2](https://github.com/zchee/go-qcow2).

- Alternative sparse disk image
- `preadv`/`pwritev` support (with [mirage/ocaml-qcow](https://github.com/mirage/ocaml-qcow) block write)
- ocaml-qcow: OCaml to C binding to cgo use Go `.syso` build
 - `.ml` -> `.cmx` -> `.o` -> `.syso` -> cgo
- Fully compatible Docker for Mac's `Docker.qcow2` qcow2 option
 - hardcoded
 - cluster-size: `65536`
 - preallocation: `false`(off)
 - AES encryption: `false`(no encryption)
 - lazy-refcount: `true`(on)
- `diskimageFooter`/`efipartfooter`
 - `[]byte` hardcoded "`SFH...disk image`" "`EFI PART`" magic string
 - See `strings /path/to/qcow2image.qcow2` or any binary editor

#### Install `ocaml-qcow`:
https://github.com/docker/hyperkit#building

#### make
`GO_BUILD_TAG='lib9p qcow2' make V=1`

#### check
`make test-bindings`
or
- lib9p: `nm bin/docker-machine-driver-xhyve | grep _l9p_server_init`
- qcow2: `nm bin/docker-machine-driver-xhyve | grep _camlMirage_block__code_begin`

### CODE REVIEW

**Comment by zchee** [comment]
/cc @dlorenc @r2d4 Please test it if you have time.
If you can't build with any problems, I will upload pre-compile binary.

**Comment by dlorenc** [comment]
I've been trying to build but running into problems with homebrew/opam. I'll keep trying today.

**Comment by r2d4** [comment]
```
-> ls ~/.minikube/machines/minikube/minikube.qcow2
/Users/mrick/.minikube/machines/minikube/minikube.qcow2
```

Works with minikube on my machine!

**Comment by dlorenc** [comment]
Feel free to merge :) @r2d4 tested and it works for him :)

**Comment by zchee** [comment]
@dlorenc I see :)
I will merge it after the fix some issue(go test, travis build).

**Comment by zchee** [comment]
@r2d4 and, Thanks for test!
It might be difficult to build from source because of OCaml dependency, so I will release pre-build binary as soon as possible.

**Pull request merged**
