### PR TITLE
Add some debug logging during mac address retrieval.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by zchee** [comment]
@dlorenc Thanks!
It's strange successful if reboot... I will continue to debug to vmnet.
LGTM.

**Comment by zchee** [comment]
passes CI. TravisCI is very slow...
merged, thanks :)

**Comment by zchee** [comment]
@dlorenc ah! I do not yet merge! sorry, could you re-open it?

**Comment by dlorenc** [comment]
Ah whoops :)

**Comment by zchee** [comment]
@dlorenc 🙇

**Pull request merged**
