### PR TITLE
Enhanced NFS shares

### PR DESCRIPTION
**Pull request by johanneswuerbach**
* Auto-remove added shares on machine remove
* Validate added share before writing to `/etc/exports`

### CODE REVIEW

**Comment by zchee** [comment]
@johanneswuerbach Wonderful...
I will test later :)

**Comment by zchee** [comment]
@johanneswuerbach 
I'm debugging of satori/go.uuid outputs occasionally illegal `uuid`.
Please wait a little :)

**Comment by zchee** [comment]
@johanneswuerbach I removed `satori/go.uuid`.
Sorry, Please rebase this PR.

**Comment by johanneswuerbach** [comment]
Rebased :-)

**Comment by zchee** [comment]
@johanneswuerbach 
LGTM.

**Pull request merged**
