### PR TITLE
Update readme to document rawdisk

### PR DESCRIPTION
**Pull request by dalehamel**
@zchee readme update as requested for https://github.com/zchee/docker-machine-driver-xhyve/pull/169

### CODE REVIEW

**Comment by zchee** [comment]
@dalehamel Thanks! merged.

**Comment by alafon** [comment]
@zchee I won't open a new issue to ask a _possible_ simple question but could you explain a bit more what using this feature implies ? It is said that there is a _potential cost of data durability_, what does that mean ? Can mounted volumes be affected/corrupted ? Or is it just about the containers _inner_ volumes ?

Thanks in advance

**Comment by dalehamel** [comment]
@alafon since I added the support for this, I'll answer.

Basically, if you are running something where data integrity really matters (MySQL perhaps), then an unclean shutdown of the VM could result in some bytes being unwritten when using this driver.

Most likely though, since you're probably using this for development, this probably doesn't matter.

This is because the `virtio-blk` is much more "raw" than the `ahci` approach, which attempts to more closely mimic how an actual SCSI device would operate.

We use virtio-blk because it is faster and lower overhead, and we make sure everything is disposable anyways (this is kubernetes after all), so we don't really care if there are some edge cases where data could be corrupted.

**Comment by alafon** [comment]
Thanks for the answer, pretty clear :)

**Pull request merged**
